package com.gokova.myanimelist.feature.details.domain.model

data class AnimeDetails(
    val id: Long,
    val displayTitle: String,
    val subtitleTitle: String?,
    val originalTitle: String,
    val englishTitle: String?,
    val mainPictureMedium: String?,
    val mainPictureLarge: String?,
    val synopsis: String?,
    val genres: List<String>,
    val themes: List<String>,
    val meanScore: Double?,
    val userScore: Int?,
    val userStatus: String?,
    val isInUserList: Boolean,
    val rank: Int?,
    val popularity: Int?,
    val numListUsers: Int?,
    val numScoringUsers: Int?,
    val mediaType: String?,
    val status: String?,
    val season: String?,
    val numEpisodes: Int?,
    val durationSeconds: Int?,
    val relatedAnime: List<RelatedAnime> = emptyList(),
    val recommendations: List<DetailRecommendation> = emptyList(),
)
